version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: trace_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - my-data://C/TraceHunterPG4
    ports:
      - "5433:5432"
volumes:
  my-data: