CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE QuestionType AS ENUM ('SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'TRUE_FALSE', 'SHORT_ANSWER', 'MATCHING', 'FILL_IN_THE_BLANK');
CREATE TYPE CompletionStatus AS ENUM ('IN_PROGRESS', 'FINISHED', 'NOT_OPENED');
CREATE TYPE ContentType AS ENUM ('COURSE', 'LECTURE', 'PRACTICE', 'QUESTION');