CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE QuestionType AS ENUM ('MULTIPLE_CHOICE', 'TRUE_FALSE', 'SHORT_ANSWER', 'ESSAY');
CREATE TYPE CompletionStatus AS ENUM ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED');
CREATE TYPE ContentType AS ENUM ('COURSE', 'LECTURE', 'PRACTICE', 'QUESTION');