create index idx_lessons_course on lessons(course_id);
create index idx_section_lesson on lesson_sections(lesson_id);
create index idx_status_user on user_status(user_id);
create index idx_user_role on users(role_id);
create index idx_status_course on user_course_status(course_id);
create index idx_practice_section on practice_content(section_id);
create index idx_test_section on test_content(section_id);
create index idx_user_sections on user_section_status(user_id);
CREATE INDEX idx_lessons_order ON lessons(course_id, order_index);
CREATE INDEX idx_sections_order ON lesson_sections(lesson_id, order_index);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_username ON users(username);