spring:
  application:
    name: footprints
    version: 1.0.0
  datasource:
    url: jdbc:postgresql://localhost:5432/trace_db
    username: admin
    password: admin
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration 
    default-schema: public
    schemas:
      - public
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    fail-on-missing-location: true

springdoc:
  swagger-ui:
    path: /swagger-ui

jwt:
  secret: 'f34360bcbe2c4a4d25b662c02ac57f4bead050ecf49279441427e7a05f0aca9d'
  expiration-milliseconds: 604800000